name: Release to github packages

on:
  release:
    types: [created]

jobs:
  call-workflow-maven-install-deploy:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-install-deploy-lib.yml@main
    with:
      package-version: ${{ github.event.release.tag_name }}
      deployment-repository: ${{ github.repository }}
      java-version: 1.8
    secrets: inherit
