name: Release to github packages

on:
  release:
    types: [created]

jobs:
  create-release:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-deploy.yml@main
    with:
      java-version: 1.8
      package-version: ${{ github.event.release.tag_name }}
      deployment-repository: ${{ github.repository }}

    secrets: inherit
